typography_spectrum: 0.6731166804675013
color:
  brandColors:
    - '#54414e'
    - '#875c74'
    - '#c5ebc3'
    - '#a790a5'
    - '#ffffff'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.15269257151521742
analytics:
  google: null
  facebook: null
  twitter: null
name: Work on Recovery
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: jfg;kdfgd
purpose: []
