name: Recoverywork
favicon: null
layout_spectrum: 0.74977
typography_spectrum: 0.6731166804675013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#54414e'
    - '#875c74'
    - '#c5ebc3'
    - '#a790a5'
    - '#ffffff'
  brandStrength: 0.019958913093432784
  lightness: 0.8892901367507875
  saturation: 0.8596927281469107
  rhythmicContrast: 0.1837946893647313
purpose: []
