name: Work on Recovery
favicon: null
layout_spectrum: 0.51671
typography_spectrum: 0.6731166804675013
title: Work on Recovery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#54414e'
    - '#875c74'
    - '#c5ebc3'
    - '#a790a5'
    - '#ffffff'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
